function safeParse(key, fallback) {
  try {
    const raw = sessionStorage.getItem(key) ?? localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch (_error) {
    sessionStorage.removeItem(key);
    localStorage.removeItem(key);
    return fallback;
  }
}

function readStoredValue(key) {
  return sessionStorage.getItem(key) || localStorage.getItem(key) || "";
}

export const state = {
  currentTopModule: "system",
  runtimeConfig: {
    app_name: "backend-center",
    run_mode: "single",
    frontend: {
      mode: "embedded",
      api_base_url: "",
    },
    cache: {
      driver: "memory",
      enabled: false,
    },
    queue: {
      driver: "memory",
      enabled: false,
    },
    health: {
      status: "ok",
      cache: { driver: "memory", healthy: true },
      queue: { driver: "memory", healthy: true },
    },
  },
  token: readStoredValue("bc_token"),
  currentUser: safeParse("bc_current_user", null),
  permissions: safeParse("bc_permissions", []),
  users: [],
  groups: [],
  roles: [],
  sources: [],
  bindings: [],
  settings: [],
  cloud: {
    summary: {
      accounts: 0,
      networks: 0,
    blueprints: 0,
    jobs: 0,
    queued_jobs: 0,
    resources: 0,
  },
  accounts: [],
  projects: [],
  environments: [],
  stacks: [],
  networkPlans: [],
  blueprints: [],
  jobs: [],
  resources: [],
  machineCredentials: [],
  machineAssets: [],
  machineGroups: [],
  },
  selectedAccessRoleID: null,
  clusters: [],
  namespaces: [],
  workloads: [],
  business: {
    view: "clusters",
    selectedClusterID: null,
    selectedClusterName: "",
    clusterListPage: "list",
    selectedNamespace: "",
    selectedWorkloadID: null,
    selectedWorkloadKind: "",
    workloadListPage: "list",
    workloadInspectorView: "overview",
    workloadManifestMode: "compact",
    selectedResourceKind: "Service",
    selectedResourceName: "",
    resourceScope: "all",
    resourceListPage: "list",
    resourceManifestMode: "compact",
    hideSystemNamespaces: false,
  },
  workloadInspector: {
    detail: null,
    rollout: null,
    resources: null,
    resourceDetail: null,
    pods: [],
    events: [],
    logs: "",
    logSourcePod: "",
    selectedPodName: "",
    manifest: "",
    followLogs: false,
    followIntervalSeconds: 5,
    execResult: null,
    interactiveTerminal: null,
    interactiveTerminalOutput: "",
    interactiveTerminalConnected: false,
    interactiveTerminalError: "",
    interactiveTerminalLastEvent: "",
    interactiveTerminalOutputBytes: 0,
  },
  resourceExplorer: {
    items: [],
    detail: null,
    manifest: "",
  },
  clusterInspector: {
    overview: null,
  },
  workloadCreator: {
    preset: "Deployment",
    mode: "builder",
    step: "basic",
    builder: null,
    resourceBuilder: null,
    yaml: null,
  },
  machine: {
    summary: {
      total_assets: 0,
      total_groups: 0,
      online_assets: 0,
      warning_assets: 0,
      offline_assets: 0,
      recent_sessions: 0,
      platform_breakup: {},
      protocol_breakup: {},
    },
    groups: [],
    credentials: [],
    quickCommands: [],
    assets: [],
    selectedAssetIDs: [],
    assetTotalItems: 0,
    assetTotalPages: 1,
    sessions: [],
    accessSidebarWidth: Number(readStoredValue("bc_machine_access_sidebar_width") || 380) || 380,
    view: "list",
    selectedAssetID: null,
    detail: null,
    accounts: [],
    assetSessions: [],
    assetEvents: [],
    terminals: [],
    activeTerminalKey: null,
    terminalSearchQuery: "",
    terminalCommandDraft: "",
    terminalSelectedTargets: [],
    selectedQuickCommandID: null,
    terminalPaneOpen: false,
    terminalPaneTab: "files",
    expandedGroups: {},
    filters: {
      search: "",
      platform: "",
      protocol: "",
      group: "",
      status: "",
      sortBy: "updated_at",
      sortOrder: "desc",
    },
    pagination: {
      page: 1,
      pageSize: 10,
      credentialsPage: 1,
      sessionsPage: 1,
    },
  },
  filters: {
    users: "",
    groups: "",
    roles: "",
    sources: "",
    bindings: "",
    settings: "",
    accessRoles: "",
    accessBindings: "",
    accessBindingType: "",
    auditSessions: "",
    auditChanges: "",
    auditChangeKind: "",
    auditEventType: "",
    auditEventLevel: "",
    clusters: "",
    namespaces: "",
    workloads: "",
    resources: "",
  },
  pagination: {
    workloads: {
      page: 1,
      pageSize: 10,
    },
    resources: {
      page: 1,
      pageSize: 10,
    },
  },
};
